---
- name: Set up Ansible's Environment
  hosts: localhost
  gather_facts: no
  
  tasks:
  - name: Add "/etc/hosts"
    blockinfile: |
      dest=/etc/hosts
      content="
      192.168.0.100 ansible-server
      192.168.0.101 ansible-node01
      192.168.0.102 ansible-node02
      192.168.0.103 ansible-node03"
      
  - name: Add "/etc/ansible/hosts"
    blockinfile: |
      dest=/etc/ansible/hosts
      content="
      [CentOS]
      ansible-node01
      ansible-node02
      
      [Ubuntu]
      ansible-node03
      
      [nodes]
      ansible-node01
      ansible-node02
      ansible-node03"
    
  - name: Install sshpass for Authentication
    yum:
      name: sshpass
      state: present
      
  - name: Install git
    yum:
      name: git
      state: present
      
  - name: Install vim
    yum:
      name: vim
      state: present
      
  - name: Configure Bashrc
    lineinfile:
      dest: /home/vagrant/.bashrc
      line: "{{ item }}"
    with_items:
    - "alias vi='vim'"
    - "alias ans='ansible'"
    - "alias anp='ansible-playbook'"
    
    