---
- hosts: nodes

  tasks:
  - name: create id_rsa.pub
    command: ssh-keygen -b 2048 -t rsa -f ~/.ssh/id_rsa -q -N ""
    connection: local
    ignore_errors: yes
    run_once: yes
  
  - name: Set authorized key taken from file
    authorized_key:
      user: vagrant
      state: present
      key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
      
  - name: CentOS chmod authorized_keys file
    file:
      path: /home/vagrant/.ssh/authorized_keys
      mode: 0600
    when: ansible_distribution == 'CentOS'