# -*- mode: ruby -*-
# vi: set ft=ruby :

IMAGE_UBUNTU = "ubuntu/bionic64"
IMAGE_CENTOS = "centos/7"
NETWORK_SUB = "192.168.56"
START_IP = 180
NODE_COUNT = 2
VM_GROUP_NAME = "Ansible-AWX"

cluster = {
  "tower" => { :mem => 2048, :cpus => 2 },
  "node" => { :mem => 1024, :cpus => 1 }
}

Vagrant.configure("2") do |config|

  # AWX Node - Ubuntu 18.04
  (1..2).each do |i|
    config.vm.define "awxnode-#{i}" do |node|
	  node.vm.box = IMAGE_UBUNTU
	  node.vm.network :private_network, ip: "#{NETWORK_SUB}.#{START_IP + i}"
	  node.vm.hostname = "awxnode-#{i}"
	  # node.vm.boot_timeout = 120
	  
	  node.vm.provider :virtualbox do |vb|
	    vb.name = "#{VM_GROUP_NAME}-node-#{i}"
	    vb.memory = cluster['node'][:mem]
	    vb.cpus = cluster['node'][:cpus]
		vb.customize ["modifyvm", :id, "--groups", "/#{VM_GROUP_NAME}"]
	  end
	  node.vm.provision "shell", path: "./scripts/permit_ssh_access_with_password.sh"
    end
  end
  # AWX Node - CentOS7
  (3..4).each do |i|
    config.vm.define "awxnode-#{i}" do |node|
	  node.vm.box = IMAGE_CENTOS
	  node.vm.network :private_network, ip: "#{NETWORK_SUB}.#{START_IP + i}"
	  node.vm.hostname = "awxnode-#{i}"
	  # node.vm.boot_timeout = 120
	  
	  node.vm.provider :virtualbox do |vb|
	    vb.name = "#{VM_GROUP_NAME}-node-#{i}"
	    vb.memory = cluster['node'][:mem]
	    vb.cpus = cluster['node'][:cpus]
		vb.customize ["modifyvm", :id, "--groups", "/#{VM_GROUP_NAME}"]
	  end
	  node.vm.provision "shell", path: "./scripts/permit_ssh_access_with_password.sh"
    end
  end
  
  
  
  # AWX Tower
  config.vm.define :awxtower, primary: true do |tower|
    tower.vm.box = IMAGE_UBUNTU
	tower.vm.network :private_network, ip: "#{NETWORK_SUB}.#{START_IP}"
    tower.vm.hostname = "awxtower"
	tower.vm.provision "shell", path: "scripts/package_install.sh"
	tower.vm.provision "file", source: "scripts/ansible_env_settings.yml", destination: "./ansible_env_settings.yml"
	tower.vm.provision "shell", inline: "ansible-playbook ansible_env_settings.yml"
	tower.vm.provision "file", source: "scripts/auto_known_hosts.yml", destination: "./auto_known_hosts.yml"
	tower.vm.provision "shell", inline: "ansible-playbook auto_known_hosts.yml", privileged: false
	tower.vm.provision "file", source: "scripts/authorized_keys.yml", destination: "authorized_keys.yml"
	tower.vm.provision "shell", inline: "ansible-playbook authorized_keys.yml -e ansible_ssh_pass=vagrant", privileged: false
	tower.vm.provision "shell", path: "./scripts/permit_ssh_access_with_password.sh"
	# tower.vm.boot_timeout = 120

	tower.vm.provider :virtualbox do |vb|
	  vb.name = "#{VM_GROUP_NAME}-tower"
	  vb.memory = cluster['tower'][:mem]
	  vb.cpus = cluster['tower'][:cpus]
	  vb.customize ["modifyvm", :id, "--groups", "/#{VM_GROUP_NAME}"]
	end
  end
end