IMAGE_NAME = "centos/7"

NETWORK_SUB = "192.168.0." # 각 환경에 맞게 설정
START_IP = 150 # 각 환경에 맞게 설정
K8S_MINOR_VERSION = 23 # 쿠버네티스 버전 선택
VM_GROUP_NAME = "k8s-1.#{K8S_MINOR_VERSION}.4-0"

cluster = {
  "master" => { :cpus => 2, :mem => 2048 }, # 각 환경에 맞게 설정
  "worker" => { :cpus => 1, :mem => 1024 }
}
KUBE_VER = "1.#{K8S_MINOR_VERSION}.4-0"
#DOCKER_VER = 


NODE_COUNT = 2

Vagrant.configure("2") do |config|
  config.vm.box = IMAGE_NAME
  
  #-------------#
  # Master Node #
  #-------------#
  config.vm.define "master", primary: true do |master|
    #master.vm.box = IMAGE_NAME
	master.vm.provider "virtualbox" do |v|
	  v.name = "#{VM_GROUP_NAME}-master"
	  v.cpus = cluster['master'][:cpus]
	  v.memory = cluster['master'][:mem]
	end
	master.vm.hostname = "master"
	master.vm.synced_folder ".", "/vagrant", type: "virtualbox"
	master.vm.network "public_network", ip: "#{NETWORK_SUB}#{START_IP}"
	master.vm.provision "shell", path: "./centos7_ssh_password_access_allow.sh"
	master.vm.provision "shell", path: "./kube.sh", env: {
	  "k8s_ver" => "#{KUBE_VER}"
	}
	master.vm.provision "shell", path: "./k8s_auto_completion.sh"
	master.vm.provision "shell", inline: <<-SHELL
	  sudo rm /vagrant/join.sh
	  sudo rm ~/.kube/config
	  sudo kubeadm init --apiserver-advertise-address=#{NETWORK_SUB}#{START_IP}
	  sudo kubeadm token create --print-join-command > /vagrant/join.sh
	  chmod u+x /vagrant/join.sh
	  mkdir -p $HOME/.kube # vagrant는 default로 sudo를 사용해서 문제되지 않는듯
      sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
      sudo chown $(id -u):$(id -g) $HOME/.kube/config
	  sudo kubectl apply -f https://projectcalico.docs.tigera.io/manifests/calico.yaml
	SHELL
  end
  
  #-------------#
  # Worker Node #
  #-------------#
  (1..NODE_COUNT).each do |i|
    config.vm.define "node-#{i}" do |node|
	  node.vm.box = IMAGE_NAME
	  node.vm.provider "virtualbox" do |v|
	    v.name = "#{VM_GROUP_NAME}-node-#{i}"
		v.cpus = cluster['worker'][:cpus]
		v.memory = cluster['worker'][:mem]
	  end
	  node.vm.hostname = "node-#{i}"
	  node.vm.synced_folder ".", "/vagrant", type: "virtualbox"
	  node.vm.network "public_network", ip: "#{NETWORK_SUB}#{START_IP + i}"
	  node.vm.provision "shell", path: "./centos7_ssh_password_access_allow.sh"
	  node.vm.provision "shell", path: "./kube.sh", env: {
	    "k8s_ver" => "#{KUBE_VER}"
	  }
	  node.vm.provision "shell", inline: <<-SHELL
	    sudo /vagrant/join.sh
	  SHELL
	end
  end
end
